name: 'gradle owasp parser'
description: 'Parse and print the OWASP Check report for gradle'
branding:
  icon: 'file-text'  
  color: 'blue'
inputs:
  path_report:
    required: true
    description: "Path to report file in json format"
  path_build_gradle:
    required: true
    description: "Path to build.gradle or build.gradle.kts"
outputs:
  vulnerability_count:
    description: 'Total count of vulnerabilities'
  vulnerable_dependencies:
    description: 'Total count of vulnerable dependencies'
  vulnerabilities:
    description: 'Comma seperated list of CVE ids'
runs:
  using: 'node12'
  main: 'out/index.js'
