name: Test

on:
  push:
    branches: [ ]

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: raynigon/gradle-owasp-parser@test/test
      with:
        path_report: "test/report.json"
        path_build_gradle: "test/build.gradle.kts"

